version: '3.9'
services:
  db:
    image: mongo:4.4.7
    restart: always
    environment:
      # mongodb client connection
      # MONGO_INITDB_ROOT_USERNAME: mongoroot
      # MONGO_INITDB_ROOT_PASSWORD: mongosecret
    ports:
      - "27017:27017"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/application"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db